### ISSUE TITLE
Create an admin login

### ISSUE THREAD

**Issue by SebastinSanty** [OSDLabs/Encore#2]
Create admin login, to administer rights to upload songs to the server.

**Comment by mukkachaitanya** [comment]
Do we even need that ?? 🤔 
Won't the server be with the admins.
Even if it isn't they can use ftp or some other method to upload songs to the server. Why do they need to login from the app _for uploading songs_ ?

**Comment by kaivalyar** [comment]
Might be useful to have a suggestions board though - where all users can ask for songs to be added, and based on request popularity, the admin may upload (via ftp?)

**Comment by mukkachaitanya** [comment]
Since we are thinking to have DC admins as our admins (are we 😛?) the suggestions board can very well be through DC++ itself.
I feel having a music app for only music would be better than making it clumsier with other unrelated features.

**Comment by SebastinSanty** [comment]
We will need a login however, in order to implement a song recommendation system and suggestions board(?). It will be just a matter of adding various levels of access now.

**Comment by kaivalyar** [comment]
I don't think the encore music suggestions should be on dc. If i'm listening to something on encore, and i feel like making a recommendation, i should be able to do it then and there, without having to open a whole new application.

**Comment by mukkachaitanya** [comment]
@SebastinSanty 
For making this I was planning to use [PassportJS](http://passportjs.org) (in particular `passport-local` module) as express itself doesn't give the options to validate user login. 
If this is fine, I will try to work on this.

**Comment by mukkachaitanya** [comment]
#7  Here

**Comment by 0xRampey** [comment]
Since this is done, song uploads can be handled in another issue.
