### ISSUE TITLE
Settings can be accessed by any client player

### ISSUE THREAD

**Issue by 0xRampey** [OSDLabs/Encore#8]
Settings can be used to change the current music directory of the server from any client player. This feature should be removed and relocated into a separate function for use only on the server.

**Comment by mukkachaitanya** [comment]
Commenting all the  un-required functionality on the client side player.

**Comment by 0xRampey** [comment]
@mukkachaitanya By _un-required_ do you mean unnecessary utilities? Because the **dangerous** **commented** functions can still be used for malicious purposes.

**Comment by SebastinSanty** [comment]
@prampey I guess this can be a sub of #9  and closed

**Comment by kaivalyar** [comment]
might still want to go through all commented code before releasing to check security ...

**Comment by mukkachaitanya** [comment]
In fact there are few other things that modify the details in the database which need to be removed from the code.
